### ISSUE TITLE
Set up github actions to build and test the project on every PR

### ISSUE THREAD

**Issue by jjant** [jjant/runty8#14]
## Description
We'd like to have all PRs checked (built/tested/linted) before merging to master.

**Comment by Asterisk-z** [comment]
I am a beginner in rust but can i take on this task?

**Comment by jjant** [comment]
Yeah, absolutely!

**Comment by Asterisk-z** [comment]
Okay
I am on it

**Comment by jjant** [comment]
Completed in #27.
