### ISSUE TITLE
Why map Z to C?

### ISSUE THREAD

**Issue by lesleyrs** [jjant/runty8#45]
https://github.com/jjant/runty8/blob/acdb734c2f892d3ed06612a5e782cddccaa75982/examples/celeste/main.rs#L485-L486

I don't mind this being a little different than pico8 but changing Z to C already hurts my brain.

**Comment by lesleyrs** [comment]
Oh that makes sense... for some reason I was thinking it was standard to use zx or cv as they're next to eachother but I guess not.

The circle button being mapped to `shift-o` instead of `shift-c` makes it a bit more confusing as well, but I get it now.

**Comment by jjant** [comment]
> The circle button being mapped to `shift-o` instead of `shift-c` makes it a bit more confusing as well, but I get it now.

Sorry, I didn't get that 🤔 I don't think I did anything with `Shift-${key}`. Could you elaborate?

**Comment by lesleyrs** [comment]
That was referring to pico-8 itself, shift-o is the circle button character.
