### ISSUE TITLE
`btn()` and `btnp()` not working consistently

### ISSUE THREAD

**Issue by lesleyrs** [jjant/runty8#61]
<s>I don't think this is a big deal but there's a problem with both `btn` functions.

`Btn`  works fine if you hold it down, but if you press repeatedly it will often ignore presses.

`Btnp` is mostly broken, ignores many key presses.

In both cases when I check by printing if they're held down it does register correctly. Even if pressing `Btnp` very slowly and the game knows it's not held down it will mostly not react to it. Can be reproduced in the game template by just changing a key to `btnp`. So is this an upstream problem?

This does not affect me because the `Btn` problem only matters if you have a game where you need very rapid key presses. `Btnp` is very clearly broken though.</s>

**Comment by lesleyrs** [comment]
Actually I'm completely wrong here, it was the frames delay I added that made it skip some input. Sorry about that.

**Comment by jjant** [comment]
Glad you got this sorted! Let's just leave the original titles in for reference/searchability.

**Comment by jjant** [comment]
This is actually a problem, `btnp` is not working consistently in the editor.
