### ISSUE TITLE
Following camera doesn't clear screen outside of the 128x128 area

### ISSUE THREAD

**Issue by lesleyrs** [jjant/runty8#63]
Was just trying to do `pico8.camera(self.x - 56, self.y - 56);` which works in pico8 but here it stops clearing screen when you're outside of the 128x128 coordinates.

Btw what is `append_camera` for?

**Comment by lesleyrs** [comment]
On top of that I'm not sure why the 2nd sprite is already being drawn 3 times on the map, it's supposed to be just the latter half of the spritesheet.

**Comment by jjant** [comment]
Can you provide a fully reproducible example?

> Btw what is `append_camera` for?

It's a convenience function I use in the editor, it adds a camera offset to the current one.
https://github.com/jjant/runty8/blob/cbb1d15a497afffe3930512b183b38cc4cf980ce/src/runty8-core/src/draw_data.rs#L39-L41

**Comment by jjant** [comment]
Thank you! Your repro helped me find the issue, this will be fixed by #66 😄
