### ISSUE TITLE
Camera position not taken into account when opening editor in game

### ISSUE THREAD

**Issue by lesleyrs** [jjant/runty8#67]
It stays in the original screen space, behavior is the same before https://github.com/jjant/runty8/commit/c915b9f637dc44bb28a3d5c7cc6496b7dbdaf19a

https://github.com/lesleyrs/runty8-game-template

**Comment by jjant** [comment]
Thanks, this should be fixed by #71.

**Comment by lesleyrs** [comment]
Yea it works thx!
